//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Exceptions.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderExceptionResourceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderExceptionResourceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Exceptions.Messages.OrderExceptionResourceMessages", typeof(OrderExceptionResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee is not registered on the barber..
        /// </summary>
        internal static string EMPLOYEE_DOES_NOT_EXISTS {
            get {
                return ResourceManager.GetString("EMPLOYEE_DOES_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to register the order due order Policy. The order doesn&apos;t match the policies for the required worker..
        /// </summary>
        internal static string INVALID_ORDER {
            get {
                return ResourceManager.GetString("INVALID_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desired order time is already alocated..
        /// </summary>
        internal static string ORDER_TIME_ALREADY_ALOCATED {
            get {
                return ResourceManager.GetString("ORDER_TIME_ALREADY_ALOCATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch alocates orders by queue, so the order time must be grather then the order now..
        /// </summary>
        internal static string ORDER_TIME_IS_BEFORE_DATE_NOW {
            get {
                return ResourceManager.GetString("ORDER_TIME_IS_BEFORE_DATE_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order is schedule for a time grather then commercial time..
        /// </summary>
        internal static string ORDER_TIME_IS_GREATER_THEN_COMMERCIAL_TIME {
            get {
                return ResourceManager.GetString("ORDER_TIME_IS_GREATER_THEN_COMMERCIAL_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order can not be scheduled during the lunch time..
        /// </summary>
        internal static string ORDER_TIME_IS_IN_LUNCH_INTERVAL {
            get {
                return ResourceManager.GetString("ORDER_TIME_IS_IN_LUNCH_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order is schedule for a time before the commercial time..
        /// </summary>
        internal static string ORDER_TIME_IS_LESS_THEN_COMMERCIAL_TIME {
            get {
                return ResourceManager.GetString("ORDER_TIME_IS_LESS_THEN_COMMERCIAL_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required order is not in commercial time..
        /// </summary>
        internal static string ORDER_TIME_IS_NOT_IN_COMMERCIAL_TIME {
            get {
                return ResourceManager.GetString("ORDER_TIME_IS_NOT_IN_COMMERCIAL_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required order time is not allowed..
        /// </summary>
        internal static string ORDER_TIME_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ORDER_TIME_NOT_ALLOWED", resourceCulture);
            }
        }
    }
}
