//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Exceptions.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScheduleExceptionMessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScheduleExceptionMessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Exceptions.Messages.ScheduleExceptionMessagesResource", typeof(ScheduleExceptionMessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date reference DayOfWeek must be equals to the Schedule DayOfWeek.
        /// </summary>
        internal static string INVALID_DATE_FOR_THIS_SCHEDULE {
            get {
                return ResourceManager.GetString("INVALID_DATE_FOR_THIS_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time or End time is invalido..
        /// </summary>
        internal static string INVALID_DATETIME {
            get {
                return ResourceManager.GetString("INVALID_DATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time and end time must be differents..
        /// </summary>
        internal static string START_TIME_AND_END_TIME_MUST_BE_DIFFERENT {
            get {
                return ResourceManager.GetString("START_TIME_AND_END_TIME_MUST_BE_DIFFERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Start time must be grater then the End time..
        /// </summary>
        internal static string START_TIME_MUST_BE_GREATER_THEN_END_TIME {
            get {
                return ResourceManager.GetString("START_TIME_MUST_BE_GREATER_THEN_END_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desired worker has no services..
        /// </summary>
        internal static string WORKER_HAS_NO_SERVICES {
            get {
                return ResourceManager.GetString("WORKER_HAS_NO_SERVICES", resourceCulture);
            }
        }
    }
}
